### ISSUE TITLE
P2 Spec Updates Thread

### ISSUE THREAD

**Issue by Faryab** [eecs370/eecs370.github.io#16]
Lets use this as a thread for any changes we need to make to P2 spec.

TODOS:
- [x] Need to update the deadlines on the top
- [x] Add link to starter files
- [x] See [here](https://eecs370.github.io/projects/p2_spec.html#36-test-cases). The hint says `Hints: the example assembly-language program above is a good case to include in your test suite`, but the examples have been moved below to [section 9](https://eecs370.github.io/projects/p2_spec.html#example-2a). We should update that.
- [x] For the [competition](https://eecs370.github.io/projects/p2_spec.html#52-competition), need to update `We are currently in the process of setting up the competition leaderboards. We appreciate the patience.` once we launch the competition.
- [x] In the [grading section](https://eecs370.github.io/projects/p2_spec.html#7-grading-auto-grading-and-formatting), update the number of daily submissions allowed.

**Comment by jackphong** [comment]
#17 Should resolve 1, 2, 3, and 5.
