### ISSUE TITLE
P3 Spec Updates

### ISSUE THREAD

**Issue by Faryab** [eecs370/eecs370.github.io#24]
Moving slack comment here for easier tracking

For the spec itself, on top of the [suggested improvements](https://docs.google.com/document/d/1z9-LwE98-lN7uDkP2HaFWW-zsCNtXb2foN-Lzs8Ds34/edit) from last semester, here are my thoughts:

- [ ] The[ lecture 12](https://eecs370.github.io/projects/p3_specs.html#21-datapath) link needs to be updated
- [ ] The [project 1](https://eecs370.github.io/projects/p3_specs.html#23-memory) link needs to be updated
- [ ] The [project 1 simulator](https://eecs370.github.io/projects/p3_specs.html#31-basic-structure) link needs to be updated
- [ ] In the [basic structure](https://eecs370.github.io/projects/p3_specs.html#31-basic-structure), I think “and state without quotes refers to the English word meaning the condition of the datapath at an instant of time” is an artifact of the old spec. Now the variable name state is not in quotes, but in `codeblocks`
- [ ] In [section 3.4](https://eecs370.github.io/projects/p3_specs.html#34-finish-your-implementation-by-accounting-for-hazards) it says “Use branch-not-taken to resolve most branch hazards”, it might be clearer to have that say “Use branch-not-taken to resolve control hazards”, most seems to imply that we sometimes don’t use branch not taken?
- [ ] In [section 4](https://eecs370.github.io/projects/p3_specs.html#4-running-your-program), the solution assembler should be linked to the p1a instructor binary in the gdrive. It currently links to a very vulnerable 370 directory...
- [ ] In [section 7](https://eecs370.github.io/projects/p3_specs.html#7-turning-in-the-project),  Change the compilation command from  gcc program.c -lm  to gcc <c_file_name> -lm -o <executable_name> . Students should know how to compile an executable with whatever name they want  :sweat_smile:

**Comment by jackphong** [comment]
For section 7, should it be gcc <c_file_name> -lm -o <executable_name> or gcc -std=c99 <c_file_name> -lm -o <executable_name>?

**Comment by hdsatam** [comment]
I highly, highly, highly, highly, highly recommend this sentence be removed from the P3 spec:  "We recommend you start with the Project 1 simulator." This sentence is causing students to fall into a trap where they think they are building upon their 1s code like they did for 1a->2a. I cannot state how strongly I feel this line should be removed from the spec. If we still feel the need to reference the 1s simulator in the spec, then the wording should be **heavily** modified to make it clear they should not be using 1s as their starting point for the code.

**Comment by jackphong** [comment]
@hdsatam Done

**Comment by Faryab** [comment]
I think we should still mention somewhere that they are encouraged to use the p1 simulator as a reference. They do use the same input mechanisms and are the best reference for running each of the instructions.

**Comment by hdsatam** [comment]
We should have a note about having them refer to 1s for input reading and general opcode execution, but we should make it very explicit that they should not be building upon that code.

**Comment by jackphong** [comment]
I like not mentioning project 1s. It should be up to students to see the connection and how p1s is similar and differences (And how they _could_ use p1s for p3). Just mentioning that p1s is your starter code is a bit misleading and can confuse students who don't understand the differences.

**Comment by Faryab** [comment]
How about something like "P1s will be a good reference as you begin to think about your implementation"

**Comment by jackphong** [comment]
How does this sound? "As you code your Project 3 Pipelined Simulator implementation, keep in mind that Project 1's Simulator is modeled after a single cycle processor"

**Comment by Faryab** [comment]
Does this issue still need to be open?

**Comment by jackphong** [comment]
I think we should leave it open - I'm going to be migrating all the project specs to use the markdown files instead of the HTML files. So I'll look back at this to see what still needs changing.

**Comment by Faryab** [comment]
Another thing to add (probably best to add to all specs)

- [ ] https://piazza.com/class/kjvo5f629u23cu?cid=3811
